<?xml version="1.0" encoding="UTF-8"?>
<!--
 # FILE:
 #   ParameterPages.py
 #
 # DESCRIPTION:
 #   Defines the parameter editing pages for the controller GUI
 #
 # SEE ALSO:
 #   Specify any related information.
 #
 # HISTORY:
 #   07-Apr-2009  sze  Initial version.
 #
 #  Copyright (c) 2009 Picarro, Inc. All rights reserved
 #
 -->

<!DOCTYPE Controller_gui [
     <!ELEMENT Controller_gui (gui_pages)>
     <!ELEMENT gui_pages (gui_page+)>
     <!ELEMENT gui_page (title,(register|mask_register|fpga_register)+)>
     <!ELEMENT register (#PCDATA)>
     <!ELEMENT mask_register (register,(mask)+)>
     <!ELEMENT fpga_register (#PCDATA)>
     <!ATTLIST fpga_register offset CDATA #REQUIRED>
     <!ELEMENT title (#PCDATA)>
     <!ELEMENT mask  (#PCDATA)>]>

<Controller_gui>
    <gui_pages>
        <gui_page>
            <title>System Parameters</title>
            <register>DAS_STATUS_REGISTER</register>
            <register>SCHEDULER_CONTROL_REGISTER</register>
            <register>RD_INITIATED_COUNT_REGISTER</register>
            <register>RD_IRQ_COUNT_REGISTER</register>
            <register>ACQ_DONE_COUNT_REGISTER</register>
            <register>RD_DATA_MOVING_COUNT_REGISTER</register>
            <register>RD_QDMA_DONE_COUNT_REGISTER</register>
            <register>RD_FITTING_COUNT_REGISTER</register>
            <register>KEEP_ALIVE_REGISTER</register>
            <register>TEMPERATURE_WINDOW_FOR_LASER_SHUTDOWN_REGISTER</register>
            <fpga_register offset="FPGA_KERNEL">OVERLOAD</fpga_register>
            <fpga_register offset="FPGA_KERNEL">CONTROL</fpga_register>
            <fpga_register offset="FPGA_KERNEL">CONFIG</fpga_register>
            <fpga_register offset="FPGA_KERNEL">DOUT_HI</fpga_register>
            <fpga_register offset="FPGA_KERNEL">DOUT_LO</fpga_register>
            <fpga_register offset="FPGA_KERNEL">DIN</fpga_register>
            <fpga_register offset="FPGA_KERNEL">INTRONIX_CLKSEL</fpga_register>
            <fpga_register offset="FPGA_KERNEL">INTRONIX_1</fpga_register>
            <fpga_register offset="FPGA_KERNEL">INTRONIX_2</fpga_register>
            <fpga_register offset="FPGA_KERNEL">INTRONIX_3</fpga_register>
            <fpga_register offset="FPGA_KERNEL">STATUS_LED</fpga_register>
            <fpga_register offset="FPGA_KERNEL">FAN</fpga_register>
            <fpga_register offset="FPGA_KERNEL">SEL_DETECTOR_MODE</fpga_register>
        </gui_page>
        <gui_page>
            <title>Laser 1 Parameters</title>
            <register>LASER1_TEMP_CNTRL_STATE_REGISTER</register>
            <register>LASER1_TEMP_CNTRL_USER_SETPOINT_REGISTER</register>
            <register>LASER1_TEMP_CNTRL_TOLERANCE_REGISTER</register>
            <register>LASER1_TEMP_CNTRL_SWEEP_MAX_REGISTER</register>
            <register>LASER1_TEMP_CNTRL_SWEEP_MIN_REGISTER</register>
            <register>LASER1_TEMP_CNTRL_SWEEP_INCR_REGISTER</register>
            <register>LASER1_TEMP_CNTRL_H_REGISTER</register>
            <register>LASER1_TEMP_CNTRL_K_REGISTER</register>
            <register>LASER1_TEMP_CNTRL_TI_REGISTER</register>
            <register>LASER1_TEMP_CNTRL_TD_REGISTER</register>
            <register>LASER1_TEMP_CNTRL_B_REGISTER</register>
            <register>LASER1_TEMP_CNTRL_C_REGISTER</register>
            <register>LASER1_TEMP_CNTRL_N_REGISTER</register>
            <register>LASER1_TEMP_CNTRL_S_REGISTER</register>
            <register>LASER1_TEMP_CNTRL_AMIN_REGISTER</register>
            <register>LASER1_TEMP_CNTRL_AMAX_REGISTER</register>
            <register>LASER1_TEMP_CNTRL_IMAX_REGISTER</register>
            <register>LASER1_TEMP_CNTRL_FFWD_REGISTER</register>
            <register>LASER1_TEC_PRBS_GENPOLY_REGISTER</register>
            <register>LASER1_TEC_PRBS_AMPLITUDE_REGISTER</register>
            <register>LASER1_TEC_PRBS_MEAN_REGISTER</register>
            <register>LASER1_MANUAL_TEC_REGISTER</register>
            <register cond="dfb1">LASER1_CURRENT_CNTRL_STATE_REGISTER</register>
            <register cond="dfb1">LASER1_MANUAL_COARSE_CURRENT_REGISTER</register>
            <register cond="dfb1">LASER1_MANUAL_FINE_CURRENT_REGISTER</register>
            <fpga_register cond="dfb1" offset="FPGA_INJECT">LASER1_FINE_CURRENT_RANGE</fpga_register>
            <register cond="dfb1">LASER1_CURRENT_SWEEP_MIN_REGISTER</register>
            <register cond="dfb1">LASER1_CURRENT_SWEEP_MAX_REGISTER</register>
            <register cond="dfb1">LASER1_CURRENT_SWEEP_INCR_REGISTER</register>
            <register cond="dfb1">LASER1_EXTRA_COARSE_SCALE_REGISTER</register>
            <register cond="dfb1">LASER1_EXTRA_FINE_SCALE_REGISTER</register>
            <register cond="dfb1">LASER1_EXTRA_OFFSET_REGISTER</register>
            <register cond="sgdbrA">SGDBR_A_CNTRL_STATE_REGISTER</register>
            <register cond="sgdbrA">SGDBR_A_CNTRL_FRONT_MIRROR_REGISTER</register>
            <register cond="sgdbrA">SGDBR_A_CNTRL_BACK_MIRROR_REGISTER</register>
            <register cond="sgdbrA">SGDBR_A_CNTRL_GAIN_REGISTER</register>
            <register cond="sgdbrA">SGDBR_A_CNTRL_SOA_REGISTER</register>
            <register cond="sgdbrA">SGDBR_A_CNTRL_COARSE_PHASE_REGISTER</register>
            <register cond="sgdbrA">SGDBR_A_CNTRL_FINE_PHASE_REGISTER</register>
            <register cond="sgdbrA">SGDBR_A_CNTRL_CHIRP_REGISTER</register>
            <register cond="sgdbrA">SGDBR_A_CNTRL_SPARE_DAC_REGISTER</register>
            <register cond="sgdbrA">SGDBR_A_CNTRL_RD_CONFIG_REGISTER</register>
            <fpga_register cond="sgdbrA" offset="FPGA_SGDBRCURRENTSOURCE_A">SYNC_REGISTER</fpga_register>
            <fpga_register cond="sgdbrA" offset="FPGA_SGDBRCURRENTSOURCE_A">MISO_DELAY</fpga_register>
            <fpga_register cond="sgdbrA" offset="FPGA_SGDBRCURRENTSOURCE_A">MAX_SYNC_CURRENT</fpga_register>
        </gui_page>
        <gui_page>
            <title>Laser 2 Parameters</title>
            <register>LASER2_TEMP_CNTRL_STATE_REGISTER</register>
            <register>LASER2_TEMP_CNTRL_USER_SETPOINT_REGISTER</register>
            <register>LASER2_TEMP_CNTRL_TOLERANCE_REGISTER</register>
            <register>LASER2_TEMP_CNTRL_SWEEP_MAX_REGISTER</register>
            <register>LASER2_TEMP_CNTRL_SWEEP_MIN_REGISTER</register>
            <register>LASER2_TEMP_CNTRL_SWEEP_INCR_REGISTER</register>
            <register>LASER2_TEMP_CNTRL_H_REGISTER</register>
            <register>LASER2_TEMP_CNTRL_K_REGISTER</register>
            <register>LASER2_TEMP_CNTRL_TI_REGISTER</register>
            <register>LASER2_TEMP_CNTRL_TD_REGISTER</register>
            <register>LASER2_TEMP_CNTRL_B_REGISTER</register>
            <register>LASER2_TEMP_CNTRL_C_REGISTER</register>
            <register>LASER2_TEMP_CNTRL_N_REGISTER</register>
            <register>LASER2_TEMP_CNTRL_S_REGISTER</register>
            <register>LASER2_TEMP_CNTRL_AMIN_REGISTER</register>
            <register>LASER2_TEMP_CNTRL_AMAX_REGISTER</register>
            <register>LASER2_TEMP_CNTRL_IMAX_REGISTER</register>
            <register>LASER2_TEMP_CNTRL_FFWD_REGISTER</register>
            <register>LASER2_TEC_PRBS_GENPOLY_REGISTER</register>
            <register>LASER2_TEC_PRBS_AMPLITUDE_REGISTER</register>
            <register>LASER2_TEC_PRBS_MEAN_REGISTER</register>
            <register>LASER2_MANUAL_TEC_REGISTER</register>
            <register cond="dfb2">LASER2_CURRENT_CNTRL_STATE_REGISTER</register>
            <register cond="dfb2">LASER2_MANUAL_COARSE_CURRENT_REGISTER</register>
            <register cond="dfb2">LASER2_MANUAL_FINE_CURRENT_REGISTER</register>
            <fpga_register cond="dfb2" offset="FPGA_INJECT">LASER2_FINE_CURRENT_RANGE</fpga_register>
            <register cond="dfb2">LASER2_CURRENT_SWEEP_MIN_REGISTER</register>
            <register cond="dfb2">LASER2_CURRENT_SWEEP_MAX_REGISTER</register>
            <register cond="dfb2">LASER2_CURRENT_SWEEP_INCR_REGISTER</register>
            <register cond="dfb2">LASER2_EXTRA_COARSE_SCALE_REGISTER</register>
            <register cond="dfb2">LASER2_EXTRA_FINE_SCALE_REGISTER</register>
            <register cond="dfb2">LASER2_EXTRA_OFFSET_REGISTER</register>
            <register cond="sgdbrC">SGDBR_C_CNTRL_STATE_REGISTER</register>
            <register cond="sgdbrC">SGDBR_C_CNTRL_FRONT_MIRROR_REGISTER</register>
            <register cond="sgdbrC">SGDBR_C_CNTRL_BACK_MIRROR_REGISTER</register>
            <register cond="sgdbrC">SGDBR_C_CNTRL_GAIN_REGISTER</register>
            <register cond="sgdbrC">SGDBR_C_CNTRL_SOA_REGISTER</register>
            <register cond="sgdbrC">SGDBR_C_CNTRL_COARSE_PHASE_REGISTER</register>
            <register cond="sgdbrC">SGDBR_C_CNTRL_FINE_PHASE_REGISTER</register>
            <register cond="sgdbrC">SGDBR_C_CNTRL_CHIRP_REGISTER</register>
            <register cond="sgdbrC">SGDBR_C_CNTRL_SPARE_DAC_REGISTER</register>
            <register cond="sgdbrC">SGDBR_C_CNTRL_RD_CONFIG_REGISTER</register>
            <fpga_register cond="sgdbrC" offset="FPGA_SGDBRCURRENTSOURCE_C">SYNC_REGISTER</fpga_register>
            <fpga_register cond="sgdbrC" offset="FPGA_SGDBRCURRENTSOURCE_C">MISO_DELAY</fpga_register>
            <fpga_register cond="sgdbrC" offset="FPGA_SGDBRCURRENTSOURCE_C">MAX_SYNC_CURRENT</fpga_register>
        </gui_page>
        <gui_page>
            <title>Laser 3 Parameters</title>
            <register>LASER3_TEMP_CNTRL_STATE_REGISTER</register>
            <register>LASER3_TEMP_CNTRL_USER_SETPOINT_REGISTER</register>
            <register>LASER3_TEMP_CNTRL_TOLERANCE_REGISTER</register>
            <register>LASER3_TEMP_CNTRL_SWEEP_MAX_REGISTER</register>
            <register>LASER3_TEMP_CNTRL_SWEEP_MIN_REGISTER</register>
            <register>LASER3_TEMP_CNTRL_SWEEP_INCR_REGISTER</register>
            <register>LASER3_TEMP_CNTRL_H_REGISTER</register>
            <register>LASER3_TEMP_CNTRL_K_REGISTER</register>
            <register>LASER3_TEMP_CNTRL_TI_REGISTER</register>
            <register>LASER3_TEMP_CNTRL_TD_REGISTER</register>
            <register>LASER3_TEMP_CNTRL_B_REGISTER</register>
            <register>LASER3_TEMP_CNTRL_C_REGISTER</register>
            <register>LASER3_TEMP_CNTRL_N_REGISTER</register>
            <register>LASER3_TEMP_CNTRL_S_REGISTER</register>
            <register>LASER3_TEMP_CNTRL_AMIN_REGISTER</register>
            <register>LASER3_TEMP_CNTRL_AMAX_REGISTER</register>
            <register>LASER3_TEMP_CNTRL_IMAX_REGISTER</register>
            <register>LASER3_TEMP_CNTRL_FFWD_REGISTER</register>
            <register>LASER3_TEC_PRBS_GENPOLY_REGISTER</register>
            <register>LASER3_TEC_PRBS_AMPLITUDE_REGISTER</register>
            <register>LASER3_TEC_PRBS_MEAN_REGISTER</register>
            <register>LASER3_MANUAL_TEC_REGISTER</register>
            <register cond="dfb3">LASER3_CURRENT_CNTRL_STATE_REGISTER</register>
            <register cond="dfb3">LASER3_MANUAL_COARSE_CURRENT_REGISTER</register>
            <register cond="dfb3">LASER3_MANUAL_FINE_CURRENT_REGISTER</register>
            <fpga_register cond="dfb3" offset="FPGA_INJECT">LASER3_FINE_CURRENT_RANGE</fpga_register>
            <register cond="dfb3">LASER3_CURRENT_SWEEP_MIN_REGISTER</register>
            <register cond="dfb3">LASER3_CURRENT_SWEEP_MAX_REGISTER</register>
            <register cond="dfb3">LASER3_CURRENT_SWEEP_INCR_REGISTER</register>
            <register cond="dfb3">LASER3_EXTRA_COARSE_SCALE_REGISTER</register>
            <register cond="dfb3">LASER3_EXTRA_FINE_SCALE_REGISTER</register>
            <register cond="dfb3">LASER3_EXTRA_OFFSET_REGISTER</register>
            <register cond="sgdbrB">SGDBR_B_CNTRL_STATE_REGISTER</register>
            <register cond="sgdbrB">SGDBR_B_CNTRL_FRONT_MIRROR_REGISTER</register>
            <register cond="sgdbrB">SGDBR_B_CNTRL_BACK_MIRROR_REGISTER</register>
            <register cond="sgdbrB">SGDBR_B_CNTRL_GAIN_REGISTER</register>
            <register cond="sgdbrB">SGDBR_B_CNTRL_SOA_REGISTER</register>
            <register cond="sgdbrB">SGDBR_B_CNTRL_COARSE_PHASE_REGISTER</register>
            <register cond="sgdbrB">SGDBR_B_CNTRL_FINE_PHASE_REGISTER</register>
            <register cond="sgdbrB">SGDBR_B_CNTRL_CHIRP_REGISTER</register>
            <register cond="sgdbrB">SGDBR_B_CNTRL_SPARE_DAC_REGISTER</register>
            <register cond="sgdbrB">SGDBR_B_CNTRL_RD_CONFIG_REGISTER</register>
            <fpga_register cond="sgdbrB" offset="FPGA_SGDBRCURRENTSOURCE_B">SYNC_REGISTER</fpga_register>
            <fpga_register cond="sgdbrB" offset="FPGA_SGDBRCURRENTSOURCE_B">MISO_DELAY</fpga_register>
            <fpga_register cond="sgdbrB" offset="FPGA_SGDBRCURRENTSOURCE_B">MAX_SYNC_CURRENT</fpga_register>
        </gui_page>
        <gui_page>
            <title>Laser 4 Parameters</title>
            <register>LASER4_TEMP_CNTRL_STATE_REGISTER</register>
            <register>LASER4_TEMP_CNTRL_USER_SETPOINT_REGISTER</register>
            <register>LASER4_TEMP_CNTRL_TOLERANCE_REGISTER</register>
            <register>LASER4_TEMP_CNTRL_SWEEP_MAX_REGISTER</register>
            <register>LASER4_TEMP_CNTRL_SWEEP_MIN_REGISTER</register>
            <register>LASER4_TEMP_CNTRL_SWEEP_INCR_REGISTER</register>
            <register>LASER4_TEMP_CNTRL_H_REGISTER</register>
            <register>LASER4_TEMP_CNTRL_K_REGISTER</register>
            <register>LASER4_TEMP_CNTRL_TI_REGISTER</register>
            <register>LASER4_TEMP_CNTRL_TD_REGISTER</register>
            <register>LASER4_TEMP_CNTRL_B_REGISTER</register>
            <register>LASER4_TEMP_CNTRL_C_REGISTER</register>
            <register>LASER4_TEMP_CNTRL_N_REGISTER</register>
            <register>LASER4_TEMP_CNTRL_S_REGISTER</register>
            <register>LASER4_TEMP_CNTRL_AMIN_REGISTER</register>
            <register>LASER4_TEMP_CNTRL_AMAX_REGISTER</register>
            <register>LASER4_TEMP_CNTRL_IMAX_REGISTER</register>
            <register>LASER4_TEMP_CNTRL_FFWD_REGISTER</register>
            <register>LASER4_TEC_PRBS_GENPOLY_REGISTER</register>
            <register>LASER4_TEC_PRBS_AMPLITUDE_REGISTER</register>
            <register>LASER4_TEC_PRBS_MEAN_REGISTER</register>
            <register>LASER4_MANUAL_TEC_REGISTER</register>
            <register cond="dfb4">LASER4_CURRENT_CNTRL_STATE_REGISTER</register>
            <register cond="dfb4">LASER4_MANUAL_COARSE_CURRENT_REGISTER</register>
            <register cond="dfb4">LASER4_MANUAL_FINE_CURRENT_REGISTER</register>
            <fpga_register cond="dfb4" offset="FPGA_INJECT">LASER4_FINE_CURRENT_RANGE</fpga_register>
            <register cond="dfb4">LASER4_CURRENT_SWEEP_MIN_REGISTER</register>
            <register cond="dfb4">LASER4_CURRENT_SWEEP_MAX_REGISTER</register>
            <register cond="dfb4">LASER4_CURRENT_SWEEP_INCR_REGISTER</register>
            <register cond="dfb4">LASER4_EXTRA_COARSE_SCALE_REGISTER</register>
            <register cond="dfb4">LASER4_EXTRA_FINE_SCALE_REGISTER</register>
            <register cond="dfb4">LASER4_EXTRA_OFFSET_REGISTER</register>
            <register cond="sgdbrD">SGDBR_D_CNTRL_STATE_REGISTER</register>
            <register cond="sgdbrD">SGDBR_D_CNTRL_FRONT_MIRROR_REGISTER</register>
            <register cond="sgdbrD">SGDBR_D_CNTRL_BACK_MIRROR_REGISTER</register>
            <register cond="sgdbrD">SGDBR_D_CNTRL_GAIN_REGISTER</register>
            <register cond="sgdbrD">SGDBR_D_CNTRL_SOA_REGISTER</register>
            <register cond="sgdbrD">SGDBR_D_CNTRL_COARSE_PHASE_REGISTER</register>
            <register cond="sgdbrD">SGDBR_D_CNTRL_FINE_PHASE_REGISTER</register>
            <register cond="sgdbrD">SGDBR_D_CNTRL_CHIRP_REGISTER</register>
            <register cond="sgdbrD">SGDBR_D_CNTRL_SPARE_DAC_REGISTER</register>
            <register cond="sgdbrD">SGDBR_D_CNTRL_RD_CONFIG_REGISTER</register>
            <fpga_register cond="sgdbrD" offset="FPGA_SGDBRCURRENTSOURCE_D">SYNC_REGISTER</fpga_register>
            <fpga_register cond="sgdbrD" offset="FPGA_SGDBRCURRENTSOURCE_D">MISO_DELAY</fpga_register>
            <fpga_register cond="sgdbrD" offset="FPGA_SGDBRCURRENTSOURCE_D">MAX_SYNC_CURRENT</fpga_register>
        </gui_page>
        <gui_page>
            <title>SGDBR A Tuning Parameters</title>
            <register cond="sgdbrA">LASER1_TEMP_CNTRL_FRONT_MIRROR_FFWD_REGISTER</register>
            <register cond="sgdbrA">LASER1_TEMP_CNTRL_BACK_MIRROR_FFWD_REGISTER</register>
            <register cond="sgdbrA">SGDBR_A_CNTRL_STATE_REGISTER</register>
            <register cond="sgdbrA">SGDBR_A_CNTRL_PULSE_FRONT_STEP_REGISTER</register>
            <register cond="sgdbrA">SGDBR_A_CNTRL_PULSE_BACK_STEP_REGISTER</register>
            <register cond="sgdbrA">SGDBR_A_CNTRL_PULSE_PHASE_STEP_REGISTER</register>
            <register cond="sgdbrA">SGDBR_A_CNTRL_PULSE_SOA_STEP_REGISTER</register>
            <register cond="sgdbrA">SGDBR_A_CNTRL_PULSE_SEMI_PERIOD_REGISTER</register>
            <register cond="sgdbrA">SGDBR_A_CNTRL_FRONT_TO_SOA_COEFF_REGISTER</register>
            <register cond="sgdbrA">SGDBR_A_CNTRL_BACK_TO_SOA_COEFF_REGISTER</register>
            <register cond="sgdbrA">SGDBR_A_CNTRL_PHASE_TO_SOA_COEFF_REGISTER</register>
            <register cond="sgdbrA">SGDBR_A_CNTRL_MIRROR_DEAD_ZONE_REGISTER</register>
            <register cond="sgdbrA">SGDBR_A_CNTRL_MINIMUM_SOA_REGISTER</register>
        </gui_page>
        <gui_page>
            <title>SGDBR B Tuning Parameters</title>
            <register cond="sgdbrB">LASER3_TEMP_CNTRL_FRONT_MIRROR_FFWD_REGISTER</register>
            <register cond="sgdbrB">LASER3_TEMP_CNTRL_BACK_MIRROR_FFWD_REGISTER</register>
            <register cond="sgdbrB">SGDBR_B_CNTRL_STATE_REGISTER</register>
            <register cond="sgdbrB">SGDBR_B_CNTRL_PULSE_FRONT_STEP_REGISTER</register>
            <register cond="sgdbrB">SGDBR_B_CNTRL_PULSE_BACK_STEP_REGISTER</register>
            <register cond="sgdbrB">SGDBR_B_CNTRL_PULSE_PHASE_STEP_REGISTER</register>
            <register cond="sgdbrB">SGDBR_B_CNTRL_PULSE_SOA_STEP_REGISTER</register>
            <register cond="sgdbrB">SGDBR_B_CNTRL_PULSE_SEMI_PERIOD_REGISTER</register>
            <register cond="sgdbrB">SGDBR_B_CNTRL_FRONT_TO_SOA_COEFF_REGISTER</register>
            <register cond="sgdbrB">SGDBR_B_CNTRL_BACK_TO_SOA_COEFF_REGISTER</register>
            <register cond="sgdbrB">SGDBR_B_CNTRL_PHASE_TO_SOA_COEFF_REGISTER</register>
            <register cond="sgdbrB">SGDBR_B_CNTRL_MIRROR_DEAD_ZONE_REGISTER</register>
            <register cond="sgdbrB">SGDBR_B_CNTRL_MINIMUM_SOA_REGISTER</register>
        </gui_page>
        <gui_page>
            <title>SGDBR C Tuning Parameters</title>
            <register cond="sgdbrC">LASER2_TEMP_CNTRL_FRONT_MIRROR_FFWD_REGISTER</register>
            <register cond="sgdbrC">LASER2_TEMP_CNTRL_BACK_MIRROR_FFWD_REGISTER</register>
            <register cond="sgdbrC">SGDBR_C_CNTRL_STATE_REGISTER</register>
            <register cond="sgdbrC">SGDBR_C_CNTRL_PULSE_FRONT_STEP_REGISTER</register>
            <register cond="sgdbrC">SGDBR_C_CNTRL_PULSE_BACK_STEP_REGISTER</register>
            <register cond="sgdbrC">SGDBR_C_CNTRL_PULSE_PHASE_STEP_REGISTER</register>
            <register cond="sgdbrC">SGDBR_C_CNTRL_PULSE_SOA_STEP_REGISTER</register>
            <register cond="sgdbrC">SGDBR_C_CNTRL_PULSE_SEMI_PERIOD_REGISTER</register>
            <register cond="sgdbrC">SGDBR_C_CNTRL_FRONT_TO_SOA_COEFF_REGISTER</register>
            <register cond="sgdbrC">SGDBR_C_CNTRL_BACK_TO_SOA_COEFF_REGISTER</register>
            <register cond="sgdbrC">SGDBR_C_CNTRL_PHASE_TO_SOA_COEFF_REGISTER</register>
            <register cond="sgdbrC">SGDBR_C_CNTRL_MIRROR_DEAD_ZONE_REGISTER</register>
            <register cond="sgdbrC">SGDBR_C_CNTRL_MINIMUM_SOA_REGISTER</register>
        </gui_page>
        <gui_page>
            <title>SGDBR D Tuning Parameters</title>
            <register cond="sgdbrD">LASER4_TEMP_CNTRL_FRONT_MIRROR_FFWD_REGISTER</register>
            <register cond="sgdbrD">LASER4_TEMP_CNTRL_BACK_MIRROR_FFWD_REGISTER</register>
            <register cond="sgdbrD">SGDBR_D_CNTRL_STATE_REGISTER</register>
            <register cond="sgdbrD">SGDBR_D_CNTRL_PULSE_FRONT_STEP_REGISTER</register>
            <register cond="sgdbrD">SGDBR_D_CNTRL_PULSE_BACK_STEP_REGISTER</register>
            <register cond="sgdbrD">SGDBR_D_CNTRL_PULSE_PHASE_STEP_REGISTER</register>
            <register cond="sgdbrD">SGDBR_D_CNTRL_PULSE_SOA_STEP_REGISTER</register>
            <register cond="sgdbrD">SGDBR_D_CNTRL_PULSE_SEMI_PERIOD_REGISTER</register>
            <register cond="sgdbrD">SGDBR_D_CNTRL_FRONT_TO_SOA_COEFF_REGISTER</register>
            <register cond="sgdbrD">SGDBR_D_CNTRL_BACK_TO_SOA_COEFF_REGISTER</register>
            <register cond="sgdbrD">SGDBR_D_CNTRL_PHASE_TO_SOA_COEFF_REGISTER</register>
            <register cond="sgdbrD">SGDBR_D_CNTRL_MIRROR_DEAD_ZONE_REGISTER</register>
            <register cond="sgdbrD">SGDBR_D_CNTRL_MINIMUM_SOA_REGISTER</register>
        </gui_page>
        <gui_page>
            <title>SOA Parameters</title>
            <register>SOA1_CURRENT_SETPOINT_REGISTER</register>
            <register>SOA1_TEMPERATURE_SETPOINT_REGISTER</register>
            <register>SOA2_CURRENT_SETPOINT_REGISTER</register>
            <register>SOA2_TEMPERATURE_SETPOINT_REGISTER</register>
            <register>SOA3_CURRENT_SETPOINT_REGISTER</register>
            <register>SOA3_TEMPERATURE_SETPOINT_REGISTER</register>
            <register>SOA4_CURRENT_SETPOINT_REGISTER</register>
            <register>SOA4_TEMPERATURE_SETPOINT_REGISTER</register>
            <register>SOA_ENABLE_MASK_REGISTER</register>
        </gui_page>
        <gui_page>
            <title>Warm Box Temperature Parameters</title>
            <register>WARM_BOX_TEMP_CNTRL_STATE_REGISTER</register>
            <register>TEC_CNTRL_REGISTER</register>
            <register>WARM_BOX_TEMP_CNTRL_USER_SETPOINT_REGISTER</register>
            <register>WARM_BOX_TEMP_CNTRL_TOLERANCE_REGISTER</register>
            <register>WARM_BOX_TEMP_CNTRL_SWEEP_MAX_REGISTER</register>
            <register>WARM_BOX_TEMP_CNTRL_SWEEP_MIN_REGISTER</register>
            <register>WARM_BOX_TEMP_CNTRL_SWEEP_INCR_REGISTER</register>
            <register>WARM_BOX_TEMP_CNTRL_H_REGISTER</register>
            <register>WARM_BOX_TEMP_CNTRL_K_REGISTER</register>
            <register>WARM_BOX_TEMP_CNTRL_TI_REGISTER</register>
            <register>WARM_BOX_TEMP_CNTRL_TD_REGISTER</register>
            <register>WARM_BOX_TEMP_CNTRL_B_REGISTER</register>
            <register>WARM_BOX_TEMP_CNTRL_C_REGISTER</register>
            <register>WARM_BOX_TEMP_CNTRL_N_REGISTER</register>
            <register>WARM_BOX_TEMP_CNTRL_S_REGISTER</register>
            <register>WARM_BOX_TEMP_CNTRL_AMIN_REGISTER</register>
            <register>WARM_BOX_TEMP_CNTRL_AMAX_REGISTER</register>
            <register>WARM_BOX_TEMP_CNTRL_IMAX_REGISTER</register>
            <register>WARM_BOX_TEMP_CNTRL_FFWD_REGISTER</register>
            <register>WARM_BOX_TEC_PRBS_GENPOLY_REGISTER</register>
            <register>WARM_BOX_TEC_PRBS_AMPLITUDE_REGISTER</register>
            <register>WARM_BOX_TEC_PRBS_MEAN_REGISTER</register>
            <register>WARM_BOX_MANUAL_TEC_REGISTER</register>
            <register>WARM_BOX_MAX_HEATSINK_TEMP_REGISTER</register>
        </gui_page>
        <gui_page>
            <title>Cavity Temperature Parameters</title>
            <register>CAVITY_TEMP_CNTRL_STATE_REGISTER</register>
            <register>TEC_CNTRL_REGISTER</register>
            <register>CAVITY_TEMP_CNTRL_USER_SETPOINT_REGISTER</register>
            <register>CAVITY_TEMP_CNTRL_TOLERANCE_REGISTER</register>
            <register>CAVITY_TEMP_CNTRL_SWEEP_MAX_REGISTER</register>
            <register>CAVITY_TEMP_CNTRL_SWEEP_MIN_REGISTER</register>
            <register>CAVITY_TEMP_CNTRL_SWEEP_INCR_REGISTER</register>
            <register>CAVITY_TEMP_CNTRL_H_REGISTER</register>
            <register>CAVITY_TEMP_CNTRL_K_REGISTER</register>
            <register>CAVITY_TEMP_CNTRL_TI_REGISTER</register>
            <register>CAVITY_TEMP_CNTRL_TD_REGISTER</register>
            <register>CAVITY_TEMP_CNTRL_B_REGISTER</register>
            <register>CAVITY_TEMP_CNTRL_C_REGISTER</register>
            <register>CAVITY_TEMP_CNTRL_N_REGISTER</register>
            <register>CAVITY_TEMP_CNTRL_S_REGISTER</register>
            <register>CAVITY_TEMP_CNTRL_AMIN_REGISTER</register>
            <register>CAVITY_TEMP_CNTRL_AMAX_REGISTER</register>
            <register>CAVITY_TEMP_CNTRL_IMAX_REGISTER</register>
            <register>CAVITY_TEMP_CNTRL_FFWD_REGISTER</register>
            <register>CAVITY_TEC_PRBS_GENPOLY_REGISTER</register>
            <register>CAVITY_TEC_PRBS_AMPLITUDE_REGISTER</register>
            <register>CAVITY_TEC_PRBS_MEAN_REGISTER</register>
            <register>CAVITY_MANUAL_TEC_REGISTER</register>
            <register>CAVITY_MAX_HEATSINK_TEMP_REGISTER</register>
            <!-->
            <register>HEATER_CNTRL_STATE_REGISTER</register>
            <register>HEATER_CNTRL_GAIN_REGISTER</register>
            <register>HEATER_CNTRL_QUANTIZE_REGISTER</register>
            <register>HEATER_CNTRL_UBIAS_SLOPE_REGISTER</register>
            <register>HEATER_CNTRL_UBIAS_OFFSET_REGISTER</register>
            <register>HEATER_CNTRL_MARK_MIN_REGISTER</register>
            <register>HEATER_CNTRL_MARK_MAX_REGISTER</register>
            <register>HEATER_CNTRL_MANUAL_MARK_REGISTER</register>
            </!-->
        </gui_page>
        <gui_page>
            <title>Heater Controller Parameters</title>
            <register>HEATER_TEMP_CNTRL_STATE_REGISTER</register>
            <register>HEATER_TEMP_CNTRL_USER_SETPOINT_REGISTER</register>
            <register>HEATER_TEMP_CNTRL_TOLERANCE_REGISTER</register>
            <register>HEATER_TEMP_CNTRL_SWEEP_MAX_REGISTER</register>
            <register>HEATER_TEMP_CNTRL_SWEEP_MIN_REGISTER</register>
            <register>HEATER_TEMP_CNTRL_SWEEP_INCR_REGISTER</register>
            <register>HEATER_TEMP_CNTRL_H_REGISTER</register>
            <register>HEATER_TEMP_CNTRL_K_REGISTER</register>
            <register>HEATER_TEMP_CNTRL_TI_REGISTER</register>
            <register>HEATER_TEMP_CNTRL_TD_REGISTER</register>
            <register>HEATER_TEMP_CNTRL_B_REGISTER</register>
            <register>HEATER_TEMP_CNTRL_C_REGISTER</register>
            <register>HEATER_TEMP_CNTRL_N_REGISTER</register>
            <register>HEATER_TEMP_CNTRL_S_REGISTER</register>
            <register>HEATER_TEMP_CNTRL_AMIN_REGISTER</register>
            <register>HEATER_TEMP_CNTRL_AMAX_REGISTER</register>
            <register>HEATER_TEMP_CNTRL_IMAX_REGISTER</register>
            <register>HEATER_PRBS_GENPOLY_REGISTER</register>
            <register>HEATER_PRBS_AMPLITUDE_REGISTER</register>
            <register>HEATER_PRBS_MEAN_REGISTER</register>
            <register>HEATER_MANUAL_MARK_REGISTER</register>
            <register>HEATER_CUTOFF_REGISTER</register>
            <!-->
            <register>HEATER_CNTRL_STATE_REGISTER</register>
            <register>HEATER_CNTRL_GAIN_REGISTER</register>
            <register>HEATER_CNTRL_QUANTIZE_REGISTER</register>
            <register>HEATER_CNTRL_UBIAS_SLOPE_REGISTER</register>
            <register>HEATER_CNTRL_UBIAS_OFFSET_REGISTER</register>
            <register>HEATER_CNTRL_MARK_MIN_REGISTER</register>
            <register>HEATER_CNTRL_MARK_MAX_REGISTER</register>
            <register>HEATER_CNTRL_MANUAL_MARK_REGISTER</register>
            </!-->
        </gui_page>
        <gui_page>
            <title>Filter Heater Parameters</title>
            <register>FILTER_HEATER_TEMP_CNTRL_STATE_REGISTER</register>
            <register>FILTER_HEATER_TEMP_CNTRL_USER_SETPOINT_REGISTER</register>
            <register>FILTER_HEATER_TEMP_CNTRL_TOLERANCE_REGISTER</register>
            <register>FILTER_HEATER_TEMP_CNTRL_SWEEP_MAX_REGISTER</register>
            <register>FILTER_HEATER_TEMP_CNTRL_SWEEP_MIN_REGISTER</register>
            <register>FILTER_HEATER_TEMP_CNTRL_SWEEP_INCR_REGISTER</register>
            <register>FILTER_HEATER_TEMP_CNTRL_H_REGISTER</register>
            <register>FILTER_HEATER_TEMP_CNTRL_K_REGISTER</register>
            <register>FILTER_HEATER_TEMP_CNTRL_TI_REGISTER</register>
            <register>FILTER_HEATER_TEMP_CNTRL_TD_REGISTER</register>
            <register>FILTER_HEATER_TEMP_CNTRL_B_REGISTER</register>
            <register>FILTER_HEATER_TEMP_CNTRL_C_REGISTER</register>
            <register>FILTER_HEATER_TEMP_CNTRL_N_REGISTER</register>
            <register>FILTER_HEATER_TEMP_CNTRL_S_REGISTER</register>
            <register>FILTER_HEATER_TEMP_CNTRL_AMIN_REGISTER</register>
            <register>FILTER_HEATER_TEMP_CNTRL_AMAX_REGISTER</register>
            <register>FILTER_HEATER_TEMP_CNTRL_IMAX_REGISTER</register>
            <register>FILTER_HEATER_TEMP_CNTRL_FFWD_REGISTER</register>
            <register>FILTER_HEATER_PRBS_GENPOLY_REGISTER</register>
            <register>FILTER_HEATER_PRBS_AMPLITUDE_REGISTER</register>
            <register>FILTER_HEATER_PRBS_MEAN_REGISTER</register>
            <register>FILTER_HEATER_MANUAL_REGISTER</register>
        </gui_page>
        <gui_page>
            <title>SGDBR Current Source Parameters</title>
            <fpga_register offset="FPGA_SGDBRMANAGER">SGDBR_PRESENT</fpga_register>
            <fpga_register offset="FPGA_SGDBRMANAGER">CSR</fpga_register>
            <fpga_register offset="FPGA_SGDBRMANAGER">CONFIG</fpga_register>
            <fpga_register offset="FPGA_SGDBRMANAGER">SCAN_SAMPLES</fpga_register>
            <fpga_register offset="FPGA_SGDBRMANAGER">SAMPLE_TIME</fpga_register>
            <fpga_register offset="FPGA_SGDBRMANAGER">DELAY_SAMPLES</fpga_register>