=== picarro-cchang/Brooks/Firmware/xml/Interface.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright Picarro, Inc 2008 -->
<!ELEMENT Das_Interface (files|interface_version|usb_constants|status_list|constant_list|struct_list|union_list|enum_list|bits_list|register_list|fpga_map_list|i2c_list|fpga_block_list|environment_list|action_list)*>
<!ELEMENT files (file+)>
<!ELEMENT file (#PCDATA)>
<!ATTLIST file ident CDATA #REQUIRED>
<!ELEMENT interface_version (#PCDATA)>
<!ELEMENT usb_constants (constant+)>
<!ELEMENT constant (#PCDATA)>
<!ATTLIST constant ident CDATA #REQUIRED>
<!ATTLIST constant description CDATA #IMPLIED>
<!ELEMENT status_list (status+)>
<!ELEMENT status (#PCDATA)>
<!ATTLIST status ident CDATA #REQUIRED>
<!ELEMENT constant_list (constant+)>
<!ELEMENT struct_list (struct+)>
<!ELEMENT struct (field+)>
<!ATTLIST struct type CDATA #REQUIRED>
<!ELEMENT field EMPTY>
<!ATTLIST field type CDATA #REQUIRED>
<!ATTLIST field ident CDATA #REQUIRED>
<!ATTLIST field size CDATA #IMPLIED>
<!ELEMENT union_list (union+)>
<!ELEMENT union (field+)>
<!ATTLIST union type CDATA #REQUIRED>
<!ELEMENT enum_list (enum+)>
<!ELEMENT enum (description,enum_value+)>
<!ATTLIST enum type CDATA #REQUIRED>
<!ELEMENT enum_value (description?)>
<!ATTLIST enum_value ident CDATA #REQUIRED>
<!ATTLIST enum_value value CDATA #IMPLIED>
<!ATTLIST enum_value caption CDATA #IMPLIED>
<!ELEMENT caption (#PCDATA)>
<!ELEMENT bits_list (bits+)>
<!ELEMENT bits (mask|shift)+>
<!ATTLIST bits ident CDATA #REQUIRED>
<!ELEMENT mask (#PCDATA)>
<!ATTLIST mask ident CDATA #REQUIRED>
<!ELEMENT shift (#PCDATA)>
<!ATTLIST shift ident CDATA #REQUIRED>
<!ELEMENT register_list (register+)>
<!ELEMENT register (description,initial?,save?,display?)>
<!ATTLIST register ident CDATA #REQUIRED>
<!ATTLIST register type CDATA #REQUIRED>
<!ATTLIST register minver CDATA #REQUIRED>
<!ATTLIST register access CDATA #REQUIRED>
<!ELEMENT description (#PCDATA)>
<!ELEMENT initial (#PCDATA)>
<!ELEMENT save EMPTY>
<!ELEMENT display (#PCDATA)>
<!ATTLIST display format CDATA #IMPLIED>
<!ATTLIST display units CDATA #IMPLIED>
<!ELEMENT fpga_map_list (fpga_map+)>
<!ELEMENT fpga_map (description)>
<!ATTLIST fpga_map ident CDATA #REQUIRED>
<!ATTLIST fpga_map index CDATA #IMPLIED>
<!ATTLIST fpga_map num CDATA #IMPLIED>
<!ATTLIST fpga_map block CDATA #IMPLIED>
<!ELEMENT environment_list (env+)>
<!ELEMENT env EMPTY>
<!ATTLIST env type CDATA #REQUIRED>
<!ATTLIST env ident CDATA #REQUIRED>
<!ELEMENT action_list (action+)>
<!ELEMENT action (#PCDATA)>
<!ATTLIST action ident CDATA #REQUIRED>
<!ELEMENT i2c_list (i2c*)>
<!ELEMENT i2c EMPTY>
<!ATTLIST i2c ident CDATA #REQUIRED>
<!ATTLIST i2c chain CDATA #REQUIRED>
<!ATTLIST i2c mux CDATA #IMPLIED>
<!ATTLIST i2c address CDATA #REQUIRED>
<!ELEMENT fpga_block_list (fpga_block+)>
<!ELEMENT fpga_block (reg+)>
<!ELEMENT reg (save*,display*,bitfield*)>
<!ELEMENT bitfield (fielddef*)>
<!ELEMENT fielddef (#PCDATA)>
<!ATTLIST fielddef value CDATA #REQUIRED>
<!ATTLIST fpga_block ident CDATA #REQUIRED>
<!ATTLIST fpga_block description CDATA #IMPLIED>
<!ATTLIST reg ident CDATA #REQUIRED>
<!ATTLIST reg type CDATA #REQUIRED>
<!ATTLIST reg description CDATA #IMPLIED>
<!ATTLIST reg access CDATA #IMPLIED>
<!ATTLIST bitfield ident CDATA #REQUIRED>
<!ATTLIST bitfield description CDATA #IMPLIED>
<!ATTLIST bitfield lsb CDATA #REQUIRED>
<!ATTLIST bitfield width CDATA #IMPLIED>

=== picarro-cchang/Brooks/xml/Interface.xml
<?xml version="1.0"?>
<!DOCTYPE Das_Interface SYSTEM "Interface.dtd">
<Das_Interface>
    <files>
        <file ident="usbPy">../host/autogen/usbdefs.py</file>
        <file ident="usbH">../CypressUSB/autogen/usbdefs.h</file>
        <file ident="usbA51">../CypressUSB/autogen/usbdefs.inc</file>
        <file ident="intH">../DSP/autogen/interface.h</file>
        <file ident="intPy">../host/autogen/interface.py</file>
        <file ident="dspC">../DSP/autogen/dspAutogen.c</file>
        <file ident="dspH">../DSP/autogen/dspAutogen.h</file>
    </files>
    <interface_version>1</interface_version>
    <usb_constants>
        <constant ident="USB_VERSION">1001</constant>
        <constant ident="INITIAL_VID">0x3EF</constant>
        <constant ident="INITIAL_PID">0x1000</constant>
        <constant ident="INSTRUMENT_VID">0x3EF</constant>
        <constant ident="INSTRUMENT_PID">0x1001</constant>
        <!--  >Vendor commands</!-->
        <constant ident="VENDOR_GET_VERSION">0xB0</constant>
        <constant ident="VENDOR_FPGA_CONFIGURE">0xC0</constant>
        <constant ident="VENDOR_READ_HPIC">0xC1</constant>
        <constant ident="VENDOR_WRITE_HPIC">0xC2</constant>
        <constant ident="VENDOR_READ_HPIA">0xC3</constant>
        <constant ident="VENDOR_WRITE_HPIA">0xC4</constant>
        <constant ident="VENDOR_SET_HPID_IN_BYTES">0xC5</constant>
        <constant ident="VENDOR_RESET_HPID_IN_FIFO">0xC6</constant>
        <constant ident="VENDOR_GET_STATUS">0xC7</constant>
        <constant ident="VENDOR_DSP_CONTROL">0xC8</constant>
        <constant ident="VENDOR_RECONNECT">0xC9</constant>
        <!--  >Value field for VENDOR_FPGA_CONFIGURE</!-->
        <constant ident="FPGA_START_PROGRAM">0x01</constant>
        <constant ident="FPGA_SEND_DATA">0x02</constant>
        <constant ident="FPGA_GET_STATUS">0x03</constant>
        <!--  >Value field for VENDOR_READ_STATUS</!-->
        <constant ident="USB_STATUS_SPEED">0x01</constant>
        <constant ident="USB_STATUS_GPIFTRIG">0x02</constant>
        <constant ident="USB_STATUS_GPIFTC">0x03</constant>
        <!--  >Value field for VENDOR_DSP_CONTROL</!-->
        <constant ident="VENDOR_DSP_CONTROL_RESET">0x01</constant>
        <constant ident="VENDOR_DSP_CONTROL_HINT">0x02</constant>
        <!--  >Bits for PORT E of Cypress USB</!-->
        <constant ident="IO_FPGA_CONF">IOE</constant>
        <constant ident="CYP_LED0">0x01</constant>
        <constant ident="CYP_LED1">0x02</constant>
        <constant ident="CYP_LED2">0x80</constant>
        <constant ident="FPGA_SS_CCLK">0x04</constant>
        <constant ident="FPGA_SS_DIN">0x08</constant>
        <constant ident="FPGA_SS_PROG">0x10</constant>
        <constant ident="FPGA_SS_INIT">0x20</constant>
        <constant ident="FPGA_SS_DONE">0x40</constant>
        <!--  >Bits for PORT A of Cypress USB</!-->
        <constant ident="CYP_LED3">0x10</constant>
    </usb_constants>
    <status_list>
        <status ident="STATUS_OK">Status OK</status>
        <status ident="ERROR_UNAVAILABLE">Data not available</status>
        <status ident="ERROR_CRC_BAD">CRC error in host command</status>
        <status ident="ERROR_DSP_UNEXPECTED_SEQUENCE_NUMBER">DSP detected host command out of sequence</status>
        <status ident="ERROR_HOST_UNEXPECTED_SEQUENCE_NUMBER">Host received acknowledgement out of sequence</status>
        <status ident="ERROR_BAD_COMMAND">Unrecognized host command</status>
        <status ident="ERROR_BAD_NUM_PARAMS">Incorrect number of parameters calling a DSP function</status>
        <status ident="ERROR_OUTSIDE_SHAREDMEM">Attempt to access outside shared memory</status>
        <status ident="ERROR_UNKNOWN_REGISTER">Invalid register specified</status>
        <status ident="ERROR_NOT_READABLE">Register is not readable</status>
        <status ident="ERROR_NOT_WRITABLE">Register is not writable</status>
        <status ident="ERROR_READ_FAILED">Register read failed</status>
        <status ident="ERROR_WRITE_FAILED">Register write failed</status>
        <status ident="ERROR_BAD_FILTER_COEFF">Invalid filter coefficients</status>
        <status ident="ERROR_BAD_VALUE">Invalid value</status>
        <status ident="ERROR_RD_BAD_RINGDOWN">Bad ringdown</status>
        <status ident="ERROR_RD_INSUFFICIENT_DATA">Insufficient data for ringdown calculation</status>
    </status_list>
    <struct_list>
        <struct type="DIAG_EventLogStruct">
            <field type="uint32" ident="time"/>
            <field type="uint32" ident="cause"/>
            <field type="uint32" ident="etalonPd1Current"/>
            <field type="uint32" ident="refPd1Current"/>
            <field type="uint32" ident="etalonPd2Current"/>
            <field type="uint32" ident="refPd2Current"/>
            <field type="uint32" ident="etalonTemp"/>
            <field type="uint32" ident="cavityTemp"/>
            <field type="uint32" ident="warmChamberTemp"/>
            <field type="uint32" ident="hotChamberTecHeatsinkTemp"/>
            <field type="uint32" ident="warmChamberTecHeatsinkTemp"/>
            <field type="uint32" ident="laser1Temp"/>
            <field type="uint32" ident="laser2Temp"/>
            <field type="uint32" ident="laserCurrent"/>
            <field type="uint32" ident="cavityPressure"/>
            <field type="uint32" ident="inletPressure"/>
            <field type="uint32" ident="outletPressure"/>
            <field type="uint16" ident="customDataArray" size="16"/>
        </struct>
        <struct type="RingdownEntryType">
            <field ident="timestamp" type="long long"/>
            <field ident="wlmAngle" type="float"/>
            <field ident="uncorrectedAbsorbance" type="float"/>
            <field ident="correctedAbsorbance" type="float"/>
            <field ident="status" type="uint16"/>
            <field ident="pztValue" type="uint16"/>
            <field ident="lockerOffset" type="uint16"/>
            <field ident="laserUsed" type="uint16"/>
            <field ident="ringdownThreshold" type="uint16"/>
            <field ident="subschemeId" type="uint16"/>
            <field ident="schemeRowAndIndex" type="uint16"/>
            <field ident="ratio1" type="uint16"/>
            <field ident="ratio2" type="uint16"/>
            <field ident="fineLaserCurrent" type="uint16"/>
            <field ident="coarseLaserCurrent" type="uint16"/>
            <field ident="laserTemperature" type="uint16"/>
            <field ident="etalonTemperature" type="uint16"/>
            <field ident="cavityPressure" type="uint16"/>
            <field ident="ambientPressure" type="uint16"/>
            <field ident="padToCacheLine" type="uint16" size="7"/>
        </struct>
        <struct type="SensorEntryType">
            <field ident="timestamp" type="long long"/>
            <field ident="streamNum" type="uint32"/>
            <field ident="value" type="DataType"/>
        </struct>
        <struct type="PidControllerEnvType">
            <field ident="swpDir" type="int32"/>
            <field ident="lockCount" type="int32"/>
            <field ident="unlockCount" type="int32"/>
            <field ident="firstIteration" type="int32"/>
            <field ident="a" type="float"/>
            <field ident="u" type="float"/>
            <field ident="perr" type="float"/>
            <field ident="derr1" type="float"/>
            <field ident="derr2" type="float"/>
            <field ident="Dincr" type="float"/>
        </struct>
        <struct type="CheckEnvType">
            <field ident="var1" type="int32"/>
            <field ident="var2" type="int32"/>
        </struct>
        <struct type="PulseGenEnvType">
            <field ident="counter" type="uint32"/>
        </struct>
        <struct type="FilterEnvType">
            <field ident="num" type="float" size="9"/>
            <field ident="den" type="float" size="9"/>
            <field ident="state" type="float" size="8"/>
        </struct>
    </struct_list>
    <constant_list>
        <constant ident="CONTROLLER_WAVEFORM_POINTS" description="Number of points in controller waveforms">1000</constant>
        <constant ident="CONTROLLER_RINGDOWN_POINTS" description="Number of points for waveforms on controller rindown pane">10000</constant>
        <constant ident="DSP_DATA_ADDRESS" description="Base address for DSP data memory">0x80800000</constant>
        <constant ident="NUM_RINGDOWN_ENTRIES" description="Number of ringdown entries">2048</constant>
        <constant ident="SHAREDMEM_ADDRESS" description="Base address for DSP shared memory">0x20000</constant>
        <constant ident="RDMEM_ADDRESS" description="Base address for ringdown memory">0xA0000000</constant>
        <constant ident="REG_OFFSET" description="Offset for software registers in DSP shared memory">0x0</constant>
        <constant ident="SENSOR_OFFSET" description="Offset for sensor stream area in DSP shared memory">0x1B00</constant>
        <constant ident="MESSAGE_OFFSET" description="Offset for message area in DSP shared memory">0x2B00</constant>
        <constant ident="GROUP_OFFSET" description="Offset for group table in DSP shared memory">0x2F00</constant>
        <constant ident="OPERATION_OFFSET" description="Offset for operation table in DSP shared memory">0x2F20</constant>
        <constant ident="OPERAND_OFFSET" description="Offset for operand table in DSP shared memory">0x3300</constant>
        <constant ident="ENVIRONMENT_OFFSET" description="Offset for environment table in DSP shared memory">0x3700</constant>
        <constant ident="HOST_OFFSET" description="Offset for host area in DSP shared memory">0x3F00</constant>
        <constant ident="SHAREDMEM_SIZE" description="Size (in 32-bit ints) of DSP shared memory">0x4000</constant>
